<?php

return array(
    [
        'id' => 'header_branding',
        'label' => 'Брендинг',
        'desc' => '',
        'type' => 'tab',
        'section' => 'header'
    ],
    [
        'id' => 'logo',
        'label' => __('Логотип', 'concrete'),
        'desc' => sprintf(__('Загрузите логотив в шапку вашего сайта', 'concrete'), 'FTP'),
//                'std'          => get_template_directory_uri() . '/assets/images/logo.png',
        'type' => 'upload',
        'section' => 'header',
        'operator' => 'and',
    ],
    [
        'id' => 'name',
        'label' => __('Наименование сайта', 'concrete'),
        'desc' => __('Введите наименование сайта', 'concrete'),
        'std' => '',
        'type' => 'text',
        'section' => 'header',
        'operator' => 'and',

    ],
    [
        'id' => 'header_buttons',
        'label' => 'Кнопки',
        'desc' => '',
        'type' => 'tab',
        'section' => 'header'
    ],
    [
        'id' => 'button_price_on_off',
        'label' => __('Кнопка "Скачать прайс"', 'concrete'),
        'desc' => __('Включить или отключить кнопку "Скачать прайс"', 'concrete'),
        'std' => 'on',
        'type' => 'on-off',
        'section' => 'header',
        'operator' => 'and',
    ],
    [
        'id' => 'caption_download_price',
        'label' => __('', 'concrete'),
        'desc' => __('Введите наименование кнопки "Скачать прайс"', 'concrete'),
        'std' => '',
        'type' => 'text',
        'section' => 'header',
        'operator' => 'and',
        'condition' => 'button_price_on_off:is(on)'
    ],
    [
        'id' => 'file_price',
        'label' => __('', 'concrete'),
        'desc' => __('Выберите файл прайса', 'concrete'),
        'std' => '',
        'type' => 'upload',
        'section' => 'header',
        'operator' => 'and',
        'condition' => 'button_price_on_off:is(on)'
    ],
    [
        'id' => 'caption_order_call',
        'label' => __('Кнопка "Телефон"', 'concrete'),
        'desc' => __('Введите наименование кнопки "Телефон"', 'concrete'),
        'std' => '',
        'type' => 'text',
        'section' => 'header',
        'operator' => 'and',

    ],
    [
        'id' => 'call',
        'label' => __('', 'concrete'),
        'desc' => __('Введите телефон для мобильных устройств"', 'concrete'),
        'std' => '',
        'type' => 'text',
        'section' => 'header',
        'operator' => 'and',
    ],
    [
        'id' => 'form_order_call',
        'label' => 'Заказ звонка',
        'desc' => '',
        'type' => 'tab',
        'section' => 'header'
    ],
    [
        'id' => 'form_order_call_on_off',
        'label' => __('Форма "Заказ звонка"', 'concrete'),
        'desc' => __('Включить или отключить форму', 'concrete'),
        'std' => 'on',
        'type' => 'on-off',
        'section' => 'header',
        'operator' => 'and',
    ],
    [
        'id' => 'form_order_call_title',
        'label' => __('Заголовок', 'concrete'),
        'desc' => __('', 'concrete'),
        'std' => '',
        'type' => 'text',
        'section' => 'header',
        'operator' => 'and',
        'condition' => 'form_order_call_on_off:is(on)'
    ],
    [
        'id' => 'order_call',
        'label' => __('Шорткод', 'concrete'),
        'desc' => __('Введите шорткод формы Contact Form 7', 'concrete'),
        'std' => '',
        'type' => 'text',
        'section' => 'header',
        'operator' => 'and',
        'condition' => 'form_order_call_on_off:is(on)'
    ],
    [
        'id' => 'footer_requisites',
        'label' => 'Реквизиты',
        'desc' => '',
        'type' => 'tab',
        'section' => 'footer'
    ],
    [
        'id' => 'footer_requisites_download_on_off',
        'label' => __('Скачать реквизиты', 'concrete'),
        'desc' => __('Включить или отключить кнопку "Скачать реквизиты"', 'concrete'),
        'std' => 'on',
        'type' => 'on-off',
        'section' => 'footer',
        'operator' => 'and',
    ],
    [
        'id' => 'requisites_file',
        'label' => __('', 'concrete'),
        'desc' => __('Выберите файл с реквизитами', 'concrete'),
        'std' => '',
        'type' => 'upload',
        'section' => 'footer',
        'operator' => 'and',
        'condition' => 'footer_requisites_download_on_off:is(on)'
    ],
    [
        'id' => 'caption_download_requisites',
        'label' => __('', 'concrete'),
        'desc' => __('Введите наименование кнопки "Скачать реквизиты"', 'concrete'),
        'std' => 'Скачать все реквизиты',
        'type' => 'text',
        'section' => 'footer',
        'operator' => 'and',
        'condition' => 'footer_requisites_download_on_off:is(on)'
    ],
    [
        'id' => 'caption_mobile_download_requisites',
        'label' => __('', 'concrete'),
        'desc' => __('Введите наименование кнопки для мобильной версии', 'concrete'),
        'std' => 'Скачать реквизиты',
        'type' => 'text',
        'section' => 'footer',
        'operator' => 'and',
        'condition' => 'footer_requisites_download_on_off:is(on)'
    ],
    [
        'id' => 'copyright',
        'label' => 'Копирайт',
        'desc' => '',
        'type' => 'tab',
        'section' => 'footer'
    ],
    [
        'id' => 'copyright_on_off',
        'label' => __('Текст копирайта', 'concrete'),
        'desc' => __('Включить или отключить текст копирайта', 'concrete'),
        'std' => 'on',
        'type' => 'on-off',
        'section' => 'footer',
        'operator' => 'and',
    ],
    [
        'id' => 'copyright_text',
        'label' => __('', 'concrete'),
        'desc' => __('Введите текст копирайта', 'concrete'),
        'std' => '',
        'type' => 'text',
        'section' => 'footer',
        'operator' => 'and',
        'condition' => 'copyright_on_off:is(on)'
    ],
    [
        'id' => 'requisites',
        'label' => 'Реквизиты',
        'desc' => '',
        'type' => 'tab',
        'section' => 'common'
    ],
    [
        'id' => 'organization',
        'label' => __('Название организации', 'concrete'),
        'desc' => __('Введите название организации', 'concrete'),
        'std' => 'ООО &laquo;МОНОЛИТ&raquo;',
        'type' => 'text',
        'section' => 'common',
        'operator' => 'and',
    ],
    [
        'id' => 'organization_man',
        'label' => __('Директор', 'concrete'),
        'desc' => __('Введите ФИО директора', 'concrete'),
        'std' => 'Тарасов Сергей Вячеславович',
        'type' => 'text',
        'section' => 'common',
        'operator' => 'and',
    ],
    [
        'id' => 'organization_ogrn',
        'label' => __('ОРГН', 'concrete'),
        'desc' => __('Введите ОРГН организации', 'concrete'),
        'std' => '1225000005339',
        'type' => 'text',
        'section' => 'common',
        'operator' => 'and',
    ],
    [
        'id' => 'organization_inn',
        'label' => __('ИНН', 'concrete'),
        'desc' => __('Введите ИНН организации', 'concrete'),
        'std' => '5044124122',
        'type' => 'text',
        'section' => 'common',
        'operator' => 'and',
    ],
    [
        'id' => 'contacts',
        'label' => 'Контакты',
        'desc' => '',
        'type' => 'tab',
        'section' => 'common'
    ],
    [
        'id' => 'contact_phone',
        'label' => __('Номер телефона', 'concrete'),
        'desc' => __('Введите номер телефона', 'concrete'),
        'std' => '8 (925) 708-88-77',
        'type' => 'text',
        'section' => 'common',
        'operator' => 'and',
    ],
    [
        'id' => 'contact_email',
        'label' => __('Электронная почта', 'concrete'),
        'desc' => __('Введите адрес электронной почты', 'concrete'),
        'std' => 'ooo.monolit2022@mail.ru',
        'type' => 'text',
        'section' => 'common',
        'operator' => 'and',
    ],
);